apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: n8n

resources:
- n8n-configmap.yaml
- n8n-deployment.yaml
- n8n-ingress-traefik.yaml
- n8n-pvc.yaml
- n8n-secrets.yaml
- n8n-service.yaml
- postgres-pvc.yaml
- postgres-secrets.yaml
- postgres-service.yaml
- postgres-statefulset.yaml
- ingress.yaml

commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"
