apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # n8n core resources
  - n8n-configmap.yaml
  - n8n-deployment.yaml
  - n8n-service.yaml
  - n8n-ingress-traefik.yaml
  - n8n-pvc.yaml
  - n8n-secrets.yaml
  

  # Optional generic ingress
  #- ingress.yaml

  # Postgres backing resources
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - postgres-pvc.yaml
  - postgres-secrets.yaml
  
