apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: kube-prometheus-stack
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/headers.custom-request-headers: "X-Forwarded-Proto:https"
    traefik.ingress.kubernetes.io/headers.custom-response-headers: "X-Frame-Options:DENY,X-Content-Type-Options:nosniff,Referrer-Policy:strict-origin-when-cross-origin"
    traefik.ingress.kubernetes.io/headers.browserXssFilter: "true"
    traefik.ingress.kubernetes.io/headers.contentTypeNosniff: "true"
    traefik.ingress.kubernetes.io/headers.forceSTSHeader: "true"
    traefik.ingress.kubernetes.io/headers.stsIncludeSubdomains: "true"
    traefik.ingress.kubernetes.io/headers.stsPreload: "true"
    traefik.ingress.kubernetes.io/headers.stsSeconds: "31536000"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - grafana.katrelleslab.org
    secretName: grafana-tls
  rules:
  - host: grafana.katrelleslab.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-grafana
            port:
              number: 80

