---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-bookmarks
  namespace: homepage
  labels:
    app: homepage
data:
  bookmarks.yaml: |
    - Development:
        - GitHub K3s:
            - href: https://github.com/SmokersCough/k3s
        - Kubernetes Dashboard:
            - href: https://kubernetes.katrelleslab.org
        - VS Code:
            - href: https://code.katrelleslab.org
        - GitLab:
            - href: https://gitlab.katrelleslab.org
    - Cloud Services:
        - Cloudflare:
            - href: https://dash.cloudflare.com
        - Docker Hub:
            - href: https://hub.docker.com
        - SonarQube:
            - href: https://sonar.katrelleslab.org
    - Documentation:
        - K3s Docs:
            - href: https://k3s.io
        - Homepage Docs:
            - href: https://gethomepage.dev
        - Kubernetes Docs:
            - href: https://kubernetes.io/docs
        - Traefik Docs:
            - href: https://doc.traefik.io/traefik
