apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: homepage

resources:
  - namespace.yaml
  - configmap-config.yaml
  - configmap-settings.yaml
  - configmap-services.yaml
  - configmap-widgets.yaml
  - configmap-bookmarks.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: homelab-infrastructure
  app.kubernetes.io/managed-by: kustomize
