apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

resources:
  - namespace.yaml

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    version: 28.0.0
    releaseName: traefik
    namespace: traefik
    valuesFile: values.yaml
    includeCRDs: true

