apiVersion: v1
kind: Endpoints
metadata:
  name: prometheus-kube-proxy
  namespace: monitoring
  labels:
    app.kubernetes.io/name: kube-prometheus-stack
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/component: kube-proxy
  annotations:
    argocd.argoproj.io/sync-wave: "2"
subsets:
- addresses:
  - ip: 192.168.50.41
  - ip: 192.168.50.42
  - ip: 192.168.50.186
  ports:
  - name: http-metrics
    port: 10249
    protocol: TCP
