apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
- namespace.yaml
- k3s-cluster-overview-configmap.yaml
- dashboard-16450-configmap.yaml

helmCharts:
- name: kube-prometheus-stack
  releaseName: prometheus
  repo: https://prometheus-community.github.io/helm-charts
  version: 77.11.1
  valuesFile: values.yaml
  includeCRDs: true

commonAnnotations:
  argocd.argoproj.io/sync-wave: "1"
  # Prevent multi-attach errors during updates
  argocd.argoproj.io/sync-options: "RespectIgnoreDifferences=true"

